#!/bin/bash -e

export REPO_HOME="http://s3-eu-west-1.amazonaws.com/fr-demo-repo/juju";
#export OIDC_MODULE="libapache2-mod-auth-openidc_1.6.0-1_amd64.deb";
export OIDC_MODULE="libapache2-mod-auth-openidc_1.7.0-1_amd64.deb";
export DOCROOT="/var/www/oidc";
export DEFAULT_CONF_FILE="/etc/apache2/sites-available/default.conf";
export OIDC_CONF_FILE="/etc/apache2/sites-available/oidc.conf";
export SSL_KEY_FILE="/etc/ssl/certs/apache.key";
export SSL_CERT_FILE="/etc/ssl/certs/apache.crt";
