#!/bin/bash -ex
. hooks/common

AGENT_NAME="OIDCAgent";
AGENT_TYPE="OAuth2Client";
REDIRECT_URI="https://$(unit-get public-address)/secret";

function joined() {
    juju-log "openidc-client-relation-joined on $JUJU_UNIT_NAME invoked $JUJU_REMOTE_UNIT";
    juju-log "REDIRECT_URI:$REDIRECT_URI";
    relation-set redirect_uri="$REDIRECT_URI";
    relation-set agent_name="$AGENT_NAME";
    relation-set agent_type="$AGENT_TYPE";
}

function changed() {
        juju-log "openidc-client-relation-changed on $JUJU_UNIT_NAME invoked $JUJU_REMOTE_UNIT";

        OPENAM_URL=$(relation-get openam_url);
        juju-log "$OPENAM_URL:'$OPENAM_URL'";
        if  [ -z "$OPENAM_URL" ]; then
            return;
        fi
        CLIENT_SECRET=$(relation-get client_secret);
        HOSTNAME_PUBLIC=$(unit-get public-address);

cat << EOF > $OIDC_CONF_FILE;
    <VirtualHost *:443>
SSLEngine on
SSLCertificateFile $SSL_CERT_FILE
SSLCertificateKeyFile $SSL_KEY_FILE

#Session On
#SessionCookieName session path=/

ServerName $HOSTNAME_PUBLIC
ErrorLog /var/log/apache2/oidc-error_log
CustomLog /var/log/apache2/oidc-access_log common
DocumentRoot $DOCROOT

LogLevel trace8

OIDCProviderIssuer $OPENAM_URL
OIDCProviderAuthorizationEndpoint $OPENAM_URL/oauth2/authorize
OIDCProviderTokenEndpoint $OPENAM_URL/oauth2/access_token
OIDCProviderTokenEndpointAuth client_secret_post
OIDCProviderUserInfoEndpoint $OPENAM_URL/oauth2/userinfo
OIDCClientID OIDCAgent
OIDCClientSecret $CLIENT_SECRET
OIDCDiscoverURL $OPENAM_URL/.well-known/openid-configuration
OIDCRedirectURI $REDIRECT_URI

OIDCSSLValidateServer Off
OIDCOAuthSSLValidateServer Off

OIDCCryptoPassphrase password2
OIDCScope "openid email profile"

<Location />
    DirectoryIndex index.php
    Authtype openid-connect
    require valid-user
</Location>
</VirtualHost>
EOF

    # Restart Apache HTTPD deamon
    a2dissite default;
    a2enmod auth_openidc;
    a2ensite oidc;
    service apache2 restart;
    open-port 443;
    close-port 80;
    juju-log "done."
}

function departed() {
	juju-log "openidc-client-relation-departed on $JUJU_UNIT_NAME invoked $JUJU_REMOTE_UNIT";
    relation-set agent_name="$AGENT_NAME";
}

function broken() {
	juju-log "openidc-client-relation-broken on $JUJU_UNIT_NAME invoked $JUJU_REMOTE_UNIT";
    # Enabling the new default initial config
    a2dissite oidc;
    a2dismod auth_openidc;
    a2ensite default;
    close-port 443;
    open-port 80;
    service apache2 restart;
}

cmd=$(basename "$0");
juju-log "CMD:$cmd:";
case "$cmd" in
	openidc-client-relation-changed)
        changed;
        ;;
	openidc-client-relation-departed)
        departed;
        ;;
    openidc-client-relation-joined)
		joined;
	;;
	openidc-client-relation-broken)
		broken;
	;;
esac
