#!/bin/bash -ex
. hooks/common
PUBLIC_HOSTNAME=$(unit-get public-address);
HOSTNAME=$(echo $PUBLIC_HOSTNAME | cut -d'.' -f1);
#AGENT_NAME="Apache24-$HOSTNAME";
AGENT_NAME="Apache24";
AGENT_TYPE="WebAgent";
APACHE_PORT=$(grep "^Listen" /etc/apache2/ports.conf | cut -d" " -f2);
AGENT_URL="http://$(unit-get public-address):$APACHE_PORT/";
AGENT_HOME="$CHARM_DIR/web_agents/apache24_agent";

function joined() {
    juju-log "openam-agent-relation-changed on $JUJU_UNIT_NAME invoked $JUJU_REMOTE_UNIT";
    
    relation-set apache_port="$APACHE_PORT";
    relation-set agent_url="$AGENT_URL";
    relation-set agent_name="$AGENT_NAME";
    relation-set agent_type="$AGENT_TYPE";
}

function changed() {
    juju-log "openam-agent-relation-changed on $JUJU_UNIT_NAME invoked $JUJU_REMOTE_UNIT";
    juju-log "CHARM_DIR:$CHARM_DIR";

    openam_url=$(relation-get openam_url);

    if [ -z "$openam_url" ]; then
        return;
    fi

    echo "$openam_url/UI/Logout" > /var/www/irm/logout.txt;

    unzip -qo $CHARM_DIR/$AGENT_FILE;
    cd $AGENT_HOME;
    echo "pacangetin" > pwd.txt;
    chmod 400 pwd.txt;


cat << ENDCONFIG > httpd_pa_config.conf
CONFIG_DIR=/etc/apache2
AM_SERVER_URL=$openam_url
AGENT_URL=$AGENT_URL
AGENT_PROFILE_NAME=$AGENT_NAME
AGENT_PASSWORD_FILE=pwd.txt
ENDCONFIG

    service apache2 stop

    chmod 755 bin/*

    if [ -d Agent_001 ];then
	   ./bin/agentadmin --uninstall --acceptLicense --useResponse httpd_pa_config.conf
    fi

    ./bin/agentadmin --install --acceptLicense --useResponse httpd_pa_config.conf

    chown -R www-data $AGENT_HOME;
    sleep 10;
    service apache2 start
    juju-log "OpenAM Apache PA installation complete."
}

function departed() {
	juju-log "openam-agent-relation-changed on $JUJU_UNIT_NAME invoked $JUJU_REMOTE_UNIT";
    relation-set agent_name="$AGENT_NAME";
}

function broken() {
	juju-log "openam-agent-relation-changed on $JUJU_UNIT_NAME invoked $JUJU_REMOTE_UNIT";
    service apache2 stop;
    cd $AGENT_HOME;
	if [ -d Agent_001 ];then
    	./bin/agentadmin --uninstall --acceptLicense --useResponse httpd_pa_config.conf
    fi
    rm -fr Agent_00?;
    rm -fr data/

    if [ -f /etc/apache2/httpd.conf ]; then rm /etc/apache2/httpd.conf;fi
    touch /etc/apache2/httpd.conf

    service apache2 start;
    juju-log "All traces of the agent removed."
}


cmd=$(basename "$0");
juju-log "CMD:$cmd:";
case "$cmd" in
	openam-agent-relation-changed)
        	changed;
        ;;
	openam-agent-relation-departed)
        	departed;
        ;;
    	openam-agent-relation-joined)
		joined;
	;;
	openam-agent-relation-broken)
		broken;
	;;
esac
