#!/bin/bash -e

export REPO_HOME="http://s3-eu-west-1.amazonaws.com/fr-demo-repo/juju";

export OPENAM_WAR="OpenAM-12.0.0-SNAPSHOT.war";
export CONFIGURATOR_FILE="SSOConfiguratorTools-12.0.0-SNAPSHOT.zip";
export SSOADM_FILE="SSOAdminTools-12.0.0-SNAPSHOT.zip";

#export OPENAM_WAR="OpenAM-11.0.2.war";
#export CONFIGURATOR_FILE="SSOConfiguratorTools-11.0.2.zip";
#export SSOADM_FILE="SSOAdminTools-11.0.2.zip";

export OPENAM_REALM="/";
export OPENAM_ADMIN="amadmin";
export PWDFILE="$CHARM_DIR/ssoadm/pwd.txt";
export SSOADM="$CHARM_DIR/ssoadm/openam/bin/ssoadm";
export JAVA_HOME=$(readlink -f $(which java) | sed "s:bin/java::");
export OPENAM_RELEASE=$(echo $OPENAM_WAR | cut -d '-' -f2 | sed 's$.war$$');
# The following will get the OpenAM version as a 4 digit number
export OPENAM_RELEASE_N=$(echo $OPENAM_RELEASE | tr -d '.')
