#!/bin/bash -ex

. hooks/common
. hooks/tomcat.sh

function install() {
	cd $CHARM_DIR;
	juju-log "Installing package unzip and tomcat7";
	# openjdk-7-jdk
#	apt-get update;
	apt-get -y -qq install unzip default-jre tomcat7;
	cp /var/lib/tomcat7/conf/server.xml /var/lib/tomcat7/conf/server.xml-org
	wget -q $REPO_HOME/$OPENAM_WAR;
	wget -q $REPO_HOME/$SSOADM_FILE;
	wget -q $REPO_HOME/$CONFIGURATOR_FILE;
}

function setupAM() {
	HTTP_PORT=$(config-get http_port);
	HOSTNAME_PUBLIC=$(unit-get public-address);
	HOSTNAME_PRIVAT=$(unit-get private-address);
	OPENAM_ADMIN="amadmin";
	OPENAM_URL="http://$HOSTNAME_PUBLIC:$HTTP_PORT";
	OPENAM_DEPLOYMENT_URI="/openam";


	cp /var/lib/tomcat7/conf/server.xml-org /var/lib/tomcat7/conf/server.xml

	if [ ! "$HTTP_PORT" -eq 8080 ]; then
		sed -i -e "s/port=\"8080\"/port=\"$HTTP_PORT\"/g" /var/lib/tomcat7/conf/server.xml;
	fi
	if [ -f /var/lib/tomcat7/webapps/ROOT/index.html ]; then
		rm /var/lib/tomcat7/webapps/ROOT/index.html
	fi
	echo "<html>" > /var/lib/tomcat7/webapps/ROOT/index.html
	echo "<head>" >> /var/lib/tomcat7/webapps/ROOT/index.html
	echo "<meta http-equiv=\"refresh\" content=\"0; url=/openam\" /> " >> /var/lib/tomcat7/webapps/ROOT/index.html
	echo "</head>" >> /var/lib/tomcat7/webapps/ROOT/index.html
	echo "</html>" >> /var/lib/tomcat7/webapps/ROOT/index.html

	open-port ${HTTP_PORT};

	juju-log "Opened port:$HTTP_PORT used by Tomcat/Openam.";

	JAVA_ARGS=$(config-get java_opts);
	juju-log "JAVA_OPTS is set to: $JAVA_ARGS";
	echo "JAVA_OPTS=\"$JAVA_ARGS\"" >>  /usr/share/tomcat7/bin/setenv.sh

	if [ -d "/root/.openamcfg" ];then
		rm -fr /root/.openamcfg;
	fi

	mkdir /root/.openamcfg;
	chown -R tomcat7 /root/.openamcfg;
	juju-log "Created .openssocfg directory for OpenAM install check.";

	if [ -d "/usr/share/tomcat7/openam" ];then
		rm -fr /usr/share/tomcat7/openam;
	fi

	mkdir /usr/share/tomcat7/openam;
    chown -R tomcat7 /usr/share/tomcat7;
	juju-log "Created default OpenAM install directory in /usr/share/tomcat7/openam";

	if [ -d /var/lib/tomcat7/webapps/openam ];then
		juju-log "Undeploying war openam"
		rm -fr /var/lib/tomcat7/webapps/openam;
		rm -f /var/lib/tomcat7/webapps/openam.war;
	fi

	tomcatObtainTomcatLock;
	tomcatStop;

	#WAR_FILE=$(ls -C1 $CHARM_DIR/*.war);
	#cp $WAR_FILE "/var/lib/tomcat7/webapps/openam.war";
	#cp $OPENAM_WAR "/var/lib/tomcat7/webapps/openam.war";
	#unzip -qqo /var/lib/tomcat7/webapps/openam.war -d /var/lib/tomcat7/webapps/openam
	unzip -qqo $OPENAM_WAR -d /var/lib/tomcat7/webapps/openam
	chown -R tomcat7 /var/lib/tomcat7/webapps;

	tomcatStart;
	tomcatReleaseTomcatLock;

	#
	# Have to wait until Tomcat has started and OpenAM id deployed
	#
	ALIVE=0
	TRY=0
	MAX=30
	#
	# Wait until ready before Tomcat is started and ready for service
	#
	until [ ! -z "$(curl --silent --show-error --connect-timeout 1 --max-time 5 -I http://localhost:$HTTP_PORT 2>/dev/null | grep 'Coyote')" ];
	do
		TRY=$[TRY+1];
		if [ "$TRY" -eq "$MAX" ]; then
			break;
		fi
        juju-log "Wait, Tomcat is restarting....."
        sleep 10
        tail -n 1 /var/lib/tomcat7/logs/catalina.out
	done

	HOSTNAME=$(unit-get public-address);
	DOMAIN=$(echo "$HOSTNAME" | awk -F "." '{print $(NF-1)"."$NF}');
	DOMAIN=$(echo $HOSTNAME_PUBLIC | cut -d"." -f2-);

	juju-log "Running configurator for fqdn '$HOSTNAME' with domain: '$DOMAIN'."

	#cd $CHARM_HOME/deploy;
	ADMIN_PWD=$(config-get amadmin_password);
	AMLDAPUSERPASSWD="pa$ADMIN_PWD";

cat << ENDCONFIG > config.conf
SERVER_URL=http://$HOSTNAME:$HTTP_PORT
DEPLOYMENT_URI=/openam
BASE_DIR=/usr/share/tomcat7/openam
locale=en_US
PLATFORM_LOCALE=en_US
AM_ENC_KEY=1234567890
ADMIN_PWD=$ADMIN_PWD
AMLDAPUSERPASSWD=$AMLDAPUSERPASSWD
COOKIE_DOMAIN=.$DOMAIN
#
DATA_STORE=embedded
DIRECTORY_SSL=SIMPLE
DIRECTORY_SERVER=$HOSTNAME
DIRECTORY_PORT=50389
DIRECTORY_ADMIN_PORT=4444
DIRECTORY_JMX_PORT=1689
ROOT_SUFFIX=dc=example,dc=com
DS_DIRMGRDN=cn=Directory Manager
DS_DIRMGRPASSWD=secret12
ENDCONFIG

if [ $OPENAM_RELEASE_N -ge 1200 ]; then
    echo "ACCEPT_LICENSES=true" >> config.conf
fi

unzip -qqo $CONFIGURATOR_FILE;
if [ ! -f "tool.jar" ]; then
	ln -s openam-configurator-tool*.jar tool.jar;
fi
java -jar tool.jar -f ./config.conf;

service tomcat7 restart;
juju-log "OpenAM configurator completed.";
}

function install-ssoadm() {
	export JAVA_HOME=$(readlink -f $(which java) | sed "s:bin/java::");
	if [ -d $CHARM_DIR/openam/ssoadm ]; then
		juju-log "Already installed.";
		return; 
	fi

	until [ ! -z "$(curl --silent --show-error --connect-timeout 1 --max-time 5 -I http://localhost:$HTTP_PORT 2>/dev/null | grep 'Coyote')" ];
	do
		TRY=$[TRY+1];
		if [ "$TRY" -eq "$MAX" ]; then
			break;
		fi
		juju-log "Wait, Tomcat is restarting.....";
		sleep 10;
		tail -n 1 /var/lib/tomcat7/logs/catalina.out;
	done

	#
	# Installing SSOAM
	#
	cd $CHARM_DIR;
	if [ -d ssoadm ]; then
		rm -fr ssoadm/
	fi
	mkdir ssoadm;
	cd ssoadm;
	unzip -qqo ../$SSOADM_FILE;
	#
	if [ -f "/usr/share/tomcat7/openam/bootstrap" ]; then
		juju-log "Installing SSOADM in '$CHARRM_DIR/ssoadm'."
		chmod 755 /usr/share/tomcat7/openam/bootstrap;
		if [ $OPENAM_RELEASE_N -gt 1102 ]; then
			./setup --acceptLicense --path /usr/share/tomcat7/openam -d $CHARM_DIR/ssoadm/ssoadm-debug -l $CHARM_DIR/ssoadm/ssoadm-log;
    	else
    		./setup --path /usr/share/tomcat7/openam -d $CHARM_DIR/ssoadm/ssoadm-debug -l $CHARM_DIR/ssoadm/ssoadm-log;
    	fi
		echo "cangetin" > $PWDFILE;
		chmod 400 $PWDFILE;
		juju-log "SSOADM installed."
	else
		juju-log --log-level ERROR "OpenAM bootstrap not found !!!!"
	fi
}

function start() {
	juju-log "START????"
}

function stop() {
	juju-log "STOP???"
}


cmd=$(basename "$0")
case "$cmd" in
	config-changed | upgrade-charm)
        setupAM;
        install-ssoadm;
        ;;
	install)
        install;
        ;;
    start)
		start;
		;;
	stop)
		stop;
		;;
esac

