#!/bin/bash -ex

. hooks/common

function changed() {
	juju-log "datastore-dj-relation-changed invoked on $JUJU_UNIT_NAME invoked $JUJU_REMOTE_UNIT";

	hostname=$(relation-get hostname);
	ldap_port=$(relation-get ldap_port);
	manager_password=$(relation-get manager_password);
	base_dn=$(relation-get base_dn);
	auth_name=$(relation-get auth_name);
	auth_type=$(relation-get auth_type);

	auth_realm="/";

	if [ -z "$hostname" ]; then
    	return;
    fi

	juju-log "hostname=$hostname, ldap_port=$ldap_port, manager_password=$manager_password, base_dn=$base_dn";
	juju-log "auth_name=$auth_name, auth_type=$auth_type, auth_realm=$auth_realm";

# -----------------------------
cat << EOF > ssoadm-batch
delete-datastores --names $auth_name --realm $auth_realm

create-realm --realm $auth_realm

create-auth-instance --name $auth_name --authtype LDAP --realm $auth_realm

update-auth-instance \
		--name $auth_name \
		--realm $auth_realm  \
		--attributevalues \
		"iplanet-am-auth-ldap-auth-level=5" \
		"iplanet-am-auth-ldap-server=$hostname:$ldap_port" \
		"iplanet-am-auth-ldap-bind-dn=cn=Directory Manager" \
		"iplanet-am-auth-ldap-bind-passwd=$manager_password" \
		"iplanet-am-auth-ldap-user-search-attributes=uid" \
		"iplanet-am-auth-ldap-user-search-attributes=mail" \
		"iplanet-am-auth-ldap-return-user-dn=false" \
		"iplanet-am-auth-ldap-base-dn=$base_dn"

create-datastore \
		--name $auth_name \
		--realm $auth_realm \
		--datatype $auth_type \
		--attributevalues \
		"sun-idrepo-ldapv3-config-authid=cn=Directory Manager" \
		"sun-idrepo-ldapv3-config-organization_name=$base_dn" \
		"sun-idrepo-ldapv3-config-ldap-server=$hostname:$ldap_port" \
		"sun-idrepo-ldapv3-config-psearchbase=$base_dn" \
		"sun-idrepo-ldapv3-config-authpw=$manager_password" \
		"sun-idrepo-ldapv3-config-people-container-name=ou" \
		"sun-idrepo-ldapv3-config-people-container-value=People"

EOF

	$SSOADM do-batch -u amadmin --password-file ${PWDFILE}  -Z ssoadm-batch --batchstatus batch-status-file --continue;

	juju-log "OpenDJ Datastore, created in OpenAM."
}

function departed() {
	juju-log "datastore-dj-relation-departed invoked on $JUJU_UNIT_NAME invoked $JUJU_REMOTE_UNIT";
	auth_name=$(relation-get auth_name);

	# Remove $OPENDJ_DATASTORE in case it already exist
	$SSOADM delete-datastores \
		--names $auth_name \
		--realm / \
		--adminid amadmin \
		--password-file ${PWDFILE} || true;
}

function joined() {
	juju-log "datastore-dj-relation-joined invoked on $JUJU_UNIT_NAME invoked $JUJU_REMOTE_UNIT";
}

function broken() {
	juju-log "datastore-dj-relation-broken invoked on $JUJU_UNIT_NAME invoked $JUJU_REMOTE_UNIT";
}


cmd=$(basename "$0")
juju-log "CMD:$cmd:";
case "$cmd" in
	datastore-dj-relation-changed)
        changed;
        ;;
	datastore-dj-relation-departed)
        departed;
        ;;
    datastore-dj-relation-joined)
		joined;
		;;
	datastore-dj-relation-broken)
		broken;
		;;
esac
