#!/bin/bash -ex

. hooks/common

function changed() {
	juju-log "db-relation-changed invoked on $SERVICE invoked $REMOTE_SERVICE";
}

function departed() {
	juju-log "db-relation-departed invoked on $SERVICE invoked $REMOTE_SERVICE";
}

function joined() {
	juju-log "db-relation-joined invoked on $SERVICE invoked $REMOTE_SERVICE";
}

function broken() {
	juju-log "db-relation-broken invoked on $SERVICE invoked $REMOTE_SERVICE";
}


cmd=$(basename "$0")
juju-log "CMD:$cmd:";
case "$cmd" in
	db-relation-changed)
        	changed;
        ;;
	db-relation-departed)
        	departed;
        ;;
    	db-relation-joined)
		joined;
		;;
	db-relation-broken)
		#broken;
		;;
esac
