#!/bin/bash -ex

readonly SERVICE=${JUJU_UNIT_NAME%\/+([0-9])};
readonly REMOTE_SERVICE=${JUJU_REMOTE_UNIT%/*};

function changed() {
	juju-log "openam-lb-relation-changed invoked $JUJU_REMOTE_UNIT";

	#juju-log "Relation settings";
	#relation-get;
	#juju-log "Relation members:";
	#relation-list;
	
	hostname=$(relation-get hostname);
	juju-log "hostname=$hostname";
}

function departed() {
	juju-log "openam-lb-relation-departed from $JUJU_REMOTE_UNIT";
}

function joined() {
	juju-log "openam-lb-relation-joined from $JUJU_REMOTE_UNIT";
	hostname=$(relation-get hostname);
}

function broken() {
	juju-log "openam-lb-relation-broken from $JUJU_REMOTE_UNIT";
}


cmd=$(basename "$0")
juju-log "CMD:$cmd:";
case "$cmd" in
	openam-lb-relation-changed)
        	changed;
        ;;
	openam-lb-relation-departed)
        	departed;
        ;;
    	openam-lb-relation-joined)
		joined;
	;;
	openam-lb-relation-broken)
		broken;
	;;
esac
