#!/bin/bash -ex
. hooks/common

function joined() {
	juju-log "openam-agent-relation-changed on $JUJU_UNIT_NAME invoked ${JUJU_REMOTE_UNIT%/*}";
	relation-set openam_url="http://$(unit-get public-address):$(config-get http_port)/openam";
	bootstrap=$(</usr/share/tomcat7/openam/bootstrap);
	relation-set bootstrap="$bootstrap";
	juju-log "openam-agent-relation-joined from $JUJU_REMOTE_UNIT";
}

function departed() {
	juju-log "openam-agent-relation-changed on $JUJU_UNIT_NAME invoked ${JUJU_REMOTE_UNIT%/*}";
}

function broken() {
	juju-log "openam-agent-relation-changed on $JUJU_UNIT_NAME invoked ${JUJU_REMOTE_UNIT%/*}";
}

function changed() {
	juju-log "openam-agent-relation-changed on $JUJU_UNIT_NAME invoked ${JUJU_REMOTE_UNIT%/*}";
}

cmd=$(basename "$0");
juju-log "CMD:$cmd:";
case "$cmd" in
	openam-agent-relation-changed)
        	changed;
        ;;
	openam-agent-relation-departed)
        	departed;
        ;;
    	openam-agent-relation-joined)
		joined;
	;;
	openam-agent-relation-broken)
		broken;
	;;
esac
