#!/bin/bash -ex

function changed() {
	juju-log "site-relation-changed invoked $JUJU_REMOTE_UNIT";	
}

function departed() {
	juju-log "ldap-relation-departed from $JUJU_REMOTE_UNIT";
}

function joined() {
	juju-log "ldap-relation-joined from $JUJU_REMOTE_UNIT";
	hostname=$(relation-get hostname);
}

function broken() {
	juju-log "ldap-relation-broken from $JUJU_REMOTE_UNIT";
}


cmd=$(basename "$0")
juju-log "CMD:$cmd:";
case "$cmd" in
	site-relation-changed)
        	changed;
        ;;
	site-relation-departed)
        	departed;
        ;;
    	site-relation-joined)
		joined;
	;;
	site-relation-broken)
		broken;
	;;
esac
