#!/bin/bash -x

OPENDJ_FILE="OpenDJ-2.6.1.zip";
FILE=opendj-preconfigured.tgz

function install() {
	REPO_HOME="http://s3-eu-west-1.amazonaws.com/fr-demo-repo";
#	apt-get -y -qq install openjdk-7-jdk unzip;
	apt-get -y -qq install default-jre;
	wget -q $REPO_HOME/latest/$OPENDJ_FILE;
#	wget -q $REPO_HOME/$FILE
	wget -q $REPO_HOME/latest/example-users.ldif.gz
#	wget -q $REPO_HOME/10K.ldif.zip
#	unzip -qqo 10K.ldif.zip
#	juju-log "$OPENDJ_FILE and 10K.ldif sample users are downloaded to '$CHARM_DIR' and ready to be used.";
}
function installOpenDJ() {
	OPENDJ_HOME=/opt/opendj;
	if [ -d /opt/opendj ]; then
		juju-log "Stopping and removing existing OpenDJ installation."
		$OPENDJ_HOME/bin/stop-ds --quiet;
		rm -fr /opt/opendj
	fi
	mkdir /opt/opendj;
	juju-log "Created OpenDJ home in '$OPENDJ_HOME'."
	tar -zxf $CHARM_DIR/$FILE -C /opt;
	open-port 1389;
	$OPENDJ_HOME/bin/start-ds --quiet;
	# Hack for the dsreplication command to be able to run as a regular user;
	mkdir -p /opt/opendj/null/config;
	ln -s /opt/opendj/config/buildinfo /opt/opendj/null/config/buildinfo;
	juju-log "OpenDJ started.";
}

function setupDJ() {
	HOSTNAME=$(unit-get public-address);
	OPENDJ_HOME=/opt/opendj;
	# Configuration parameters
	MANAGER_PWD=$(config-get manager_password);
	BASE_DN=$(config-get base_dn);
	LDAP_PORT=$(config-get ldap_port);
	REST_PORT=$(config-get rest_port);

	if [ -d /opt/opendj ]; then
		juju-log "Stopping and removing existing OpenDJ installation."
		$OPENDJ_HOME/bin/stop-ds --quiet;
		rm -fr /opt/opendj
	fi
	mkdir /opt/opendj;
	juju-log "Created OpenDJ home in '$OPENDJ_HOME'."

	unzip -qq $OPENDJ_FILE -d /opt
	juju-log "OpenDJ archive '$CHARM_HOME/$FILE' is unpacked into $OPENDJ_HOME.";

	juju-log "Configuring OpenDJ....."
	$OPENDJ_HOME/setup -i -n \
		-b $BASE_DN \
		-h $HOSTNAME \
		-p $LDAP_PORT \
		-a \
    	--adminConnectorPort 5555 \
    	--generateSelfSignedCertificate \
    	--acceptLicense \
    	-D 'cn=Directory Manager' \
    	-w $MANAGER_PWD \
    	-q -O &>/tmp/opendj-install-log;

    #
    # Importing sample users
    #
	juju-log "Importing sample userdata.";
	gunzip example-users.ldif.gz
	$OPENDJ_HOME/bin/import-ldif -l example-users.ldif -n userRoot &>/dev/null
#	$OPENDJ_HOME/bin/import-ldif -l 10K.ldif -n userRoot &>/dev/null
	#
	# Open port and start OpenDJ deamon
	#
    open-port $LDAP_PORT;
    juju-log "Port $LDAP_PORT open for DLAP requests.";
	$OPENDJ_HOME/bin/start-ds --quiet;
	juju-log "OpenDJ started.";
	#
	# Enable the REST connection handler
	#
	juju-log "Enabling the REST connection handler listening on port $OPENDJ_REST_PORT"
	$OPENDJ_HOME/bin/dsconfig set-connection-handler-prop \
		--hostname $HOSTNAME \
		--port 5555 \
 		--bindDN 'cn=Directory Manager' \
 		--bindPassword $MANAGER_PWD \
 		--handler-name "HTTP Connection Handler" \
 		--set listen-port:$REST_PORT \
 		--set enabled:true \
 		--no-prompt \
 		--trustAll;

	open-port $REST_PORT;
	juju-log "REST service installed and port '$REST_PORT' open for incoming requests.";
	#
	# Enable the HTTP access log.
	#
	juju-log "Enabling the HTTP access log.";
	$OPENDJ_HOME/bin/dsconfig set-log-publisher-prop \
 		--hostname $HOSTNAME \
 		--port 5555 \
 		--bindDN 'cn=Directory Manager' \
 		--bindPassword $MANAGER_PWD \
 		--publisher-name "File-Based HTTP Access Logger" \
 		--set enabled:true \
 		--no-prompt \
 		--trustAll;
	juju-log "Done, configuring OpenDJ.";
}

function start() {
	#$OPENDJ_HOME/bin/start-ds --quiet;
	juju-log "START???";
}

function stop() {
	#$OPENDJ_HOME/bin/stop-ds --quiet;
	juju-log "STOP???";
}

cmd=$(basename "$0")
case "$cmd" in
	config-changed | upgrade-charm)
        #installOpenDJ;
        setupDJ;
        ;;
	install)
        install;
        ;;
    start)
		start;
		;;
	stop)
		stop;
		;;
esac
