#!/bin/bash -ex
AUTH_NAME="opendj";
AUTH_TYPE="LDAPv3ForOpenDS";

function changed() {
	juju-log "datastore-dj-relation-changed invoked on $JUJU_UNIT_NAME invoked $JUJU_REMOTE_UNIT";
}

function departed() {
	juju-log "datastore-dj-relation-departed invoked on $JUJU_UNIT_NAME invoked $JUJU_REMOTE_UNIT";
	relation-set auth_name=$AUTH_NAME;
}

function joined() {
	juju-log "datastore-dj-relation-joined invoked on $JUJU_UNIT_NAME invoked $JUJU_REMOTE_UNIT";

	relation-set base_dn=$(config-get base_dn);
	relation-set ldap_port=$(config-get ldap_port);
	relation-set manager_password=$(config-get manager_password);
	relation-set hostname=$(unit-get private-address);
	relation-set auth_name=$AUTH_NAME;
	relation-set auth_type=$AUTH_TYPE;
}


function broken() {
	juju-log "datastore-dj-relation-broken invoked on $JUJU_UNIT_NAME invoked $JUJU_REMOTE_UNIT";
}

cmd=$(basename "$0")
juju-log "CMD:$cmd:";
case "$cmd" in
	datastore-dj-relation-changed)
        changed;
        ;;
	datastore-dj-relation-departed)
        departed;
        ;;
    datastore-dj-relation-joined)
		joined;
		;;
	datastore-dj-relation-broken)
		broken;
		;;
esac
