#!/bin/bash -x

OPENDJ_FILE="OpenDJ-2.6.1.zip";
OPENDJ_HOME=/opt/opendj;

function install() {
	LICENSE_ACCEPTED=$(config-get accept_license);
	juju-log "LICENSE_ACCEPTED:$LICENSE_ACCEPTED";
	if [ "${LICENSE_ACCEPTED}" != "True" ]; then
		juju-log "License has to be accepted before installing."
		exit 1
	fi
	REPO_HOME="http://s3-eu-west-1.amazonaws.com/fr-demo-repo/juju";
	apt-get -y -qq install unzip default-jre;
	wget -q $REPO_HOME/$OPENDJ_FILE;
	wget -q $REPO_HOME/example-users.ldif.gz
}

function setupDJ() {
	HOSTNAME=$(unit-get public-address);
	# Configuration parameters
	MANAGER_PWD=$(config-get manager_password);
	if [ -z "${MANAGER_PWD}" ]; then
		juju-log "OpenDJ manager password has to be set before been installed."
		exit 1
	fi

	BASE_DN=$(config-get base_dn);
	LDAP_PORT=$(config-get ldap_port);
	

	if [ -d /opt/opendj ]; then
		juju-log "Stopping and removing existing OpenDJ installation."
		$OPENDJ_HOME/bin/stop-ds --quiet;
		rm -fr /opt/opendj
	fi
	mkdir /opt/opendj;
	juju-log "Created OpenDJ home in '$OPENDJ_HOME'."

	unzip -qq $OPENDJ_FILE -d /opt
	juju-log "OpenDJ archive '$CHARM_HOME/$FILE' is unpacked into $OPENDJ_HOME.";

	juju-log "Configuring OpenDJ....."
	$OPENDJ_HOME/setup -i -n \
		-b $BASE_DN \
		-h $HOSTNAME \
		-p $LDAP_PORT \
		-a \
    	--adminConnectorPort 5555 \
    	--generateSelfSignedCertificate \
    	--acceptLicense \
    	-D 'cn=Directory Manager' \
    	-w $MANAGER_PWD \
    	-q -O &>/tmp/opendj-install-log;

    #
    # Importing sample users
    #
	juju-log "Importing sample userdata.";
	gunzip example-users.ldif.gz
	$OPENDJ_HOME/bin/import-ldif -l example-users.ldif -n userRoot &>/dev/null
	#
	# Open port and start OpenDJ deamon
	#
    open-port $LDAP_PORT;
    juju-log "Port $LDAP_PORT open for DLAP requests.";
	start;
	#
	# Enable the REST connection handler
	#
	
	REST_ENABLED=$(config-get rest_enabled);
	if [ "${REST_ENABLED}" != "False" ]; then
		REST_PORT=$(config-get rest_port);

		juju-log "Enabling the REST connection handler listening on port $OPENDJ_REST_PORT"
		$OPENDJ_HOME/bin/dsconfig set-connection-handler-prop \
			--hostname $HOSTNAME \
			--port 5555 \
 			--bindDN 'cn=Directory Manager' \
 			--bindPassword $MANAGER_PWD \
 			--handler-name "HTTP Connection Handler" \
 			--set listen-port:$REST_PORT \
 			--set enabled:true \
 			--no-prompt \
 			--trustAll;

		open-port $REST_PORT;
		juju-log "REST service installed and port '$REST_PORT' open for incoming requests.";
	fi
	#
	# Enabling the HTTP access log.
	#
	ACCESS_LOGGING=$(config-get access_logging);
	if [ "${ACCESS_LOGGING}" != "False" ]; then
		juju-log "Enabling the HTTP access log.";
		$OPENDJ_HOME/bin/dsconfig set-log-publisher-prop \
 			--hostname $HOSTNAME \
 			--port 5555 \
 			--bindDN 'cn=Directory Manager' \
 			--bindPassword $MANAGER_PWD \
 			--publisher-name "File-Based HTTP Access Logger" \
 			--set enabled:true \
 			--no-prompt \
 			--trustAll;
 	fi
	juju-log "Done, configuring OpenDJ.";
}

function start() {
#	if [ ! -f "$OPENDJ_HOME/./locks/server.lock" ]; then
#		$OPENDJ_HOME/bin/start-ds --quiet;
#	fi
	$OPENDJ_HOME/bin/start-ds --quiet;
	juju-log "OpenDJ running.";
}

function stop() {
	$OPENDJ_HOME/bin/stop-ds --quiet;
	juju-log "OpenDJ stopped.";
}

cmd=$(basename "$0")
case "$cmd" in
	config-changed | upgrade-charm)
        #installOpenDJ;
        setupDJ;
        ;;
	install)
        install;
        ;;
    start)
		start;
		;;
	stop)
		stop;
		;;
esac
